version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting Kics scan
      - docker run -v $PWD:/path checkmarx/kics scan --no-progress -p /path -o /path --output-name kics-report
  build:
    commands:
      - echo Build started on `date`
reports:
  kics-report:
    files:
      - kics-report.json
